# Generated by Django 3.0.5 on 2020-05-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='complated',
            new_name='completed',
        ),
    ]
